import setuptools

with open("README.md", "r", encoding="utf-8") as fh:
    long_description = fh.read()

setuptools.setup(
    name="Auto-Research",
    version="1.0",
    author="Sidharth Pal",
    author_email="sidharth.pal1992@gmail.com",
    description="Geberate scientific survey with just a query",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/sidphbot/Auto-Research",
    project_urls={
        "Docs" : "https://github.com/example/example/README.md",
        "Bug Tracker": "https://github.com/sidphbot/Auto-Research/issues",
        "Demo": "https://www.kaggle.com/sidharthpal/auto-research-generate-survey-from-query",
    },
    classifiers=[
        "Development Status :: 5 - Production/Stable",
        "Environment :: Console",
        "Environment :: Other Environment",
        "Intended Audience :: Developers",
        "Intended Audience :: Researchers",
        "Intended Audience :: Other Audience",
        "Natural Language :: English",
        "License :: OSI Approved :: GNU General Public License (GPL)",
        "License :: OSI Approved :: GNU Library or Lesser General Public License (LGPL)",
        "License :: OSI Approved :: GNU Lesser General Public License v3 or later (LGPLv3+)",
        "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: POSIX :: Linux",
        "Operating System :: MacOS :: MacOS X",
        "Programming Language :: Python",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3 :: Only",
        "Programming Language :: Python :: 3.6",
    ],
    package_dir={"": "src"},
    packages=setuptools.find_packages(where="src"),
    python_requires=">=3.7",
    install_requires=[
        "pip",
        "boto3==1.9.118",
        "requests==2.20.0",
        "unicodedata2==11.0.0",
        "https://github.com/jaepil/pdfminer3k/archive/1.0.4.zip",
        "sentence-transformers",
        "pdftotext",
        "arxiv",
        "arxiv2bib",
        "scholarly",
        "PyMuPDF==1.18.14",
        "Pillow",
        "tabula-py",
        "sentencepiece",
        "keybert",
        "spacy[all]",
        "scispacy",
        "amrlib",
        "transformers",
        "neuralcoref",
        "https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.4.0/en_core_sci_scibert-0.4.0.tar.gz",
        "https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.4.0/en_core_sci_lg-0.4.0.tar.gz",
        "bert-extractive-summarizer",

    ],
    tests_require=["pytest"],
)